# Use an official pgAdmin runtime as a parent image
FROM dpage/pgadmin4

# Set the working directory to /pgadmin4
WORKDIR /pgadmin4

# Copy the server details into the container at /pgadmin4
COPY servers.json /pgadmin4
