ALTER TABLE public.data_pnt DROP CONSTRAINT msrmnt_data_pnt;
ALTER TABLE public.msrmnt DROP CONSTRAINT dev_msrmnt;
ALTER TABLE public.msrmnt DROP CONSTRAINT msrmnt_dev_type;
ALTER TABLE public.msrmnt_data DROP CONSTRAINT msrmnt_data_state_check;
ALTER TABLE public.data_pnt DROP CONSTRAINT data_pnt_pk;
ALTER TABLE public.dev DROP CONSTRAINT dev_pk;
ALTER TABLE public.dev_type DROP CONSTRAINT dev_type_pk;
ALTER TABLE public.msrmnt DROP CONSTRAINT msrmnt_pk;
ALTER TABLE public.msrmnt_data DROP CONSTRAINT msrmnt_data_pk;
ALTER TABLE public.dev_type DROP CONSTRAINT dev_type_uk;


DROP VIEW ALERTS;
DROP VIEW SPLUNK_LOOKUP_DATA;
DROP TABLE DATA_PNT CASCADE;
DROP TABLE DEV CASCADE;
DROP TABLE DEV_TYPE CASCADE;
DROP TABLE MSRMNT CASCADE;
DROP TABLE MSRMNT_TYPE;
DROP TABLE MSRMNT_DATA CASCADE;