package au.com.teamarrow.model;

// Generated 02/08/2013 12:30:48 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * DeviceType generated by hbm2java
 */
@Entity
@Table(name = "dev_type", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "dev_type"))
public class DeviceType implements java.io.Serializable {

	private static final long serialVersionUID = -8497498103867367319L;
	
	private long id;
    private String type;
    private Set<Measurement> measurements = new HashSet<Measurement>(0);

    public DeviceType() {
    }

    public DeviceType(long id) {
        this.id = id;
    }

    public DeviceType(long id, String type, Set<Measurement> measurements) {
        this.id = id;
        this.type = type;
        this.measurements = measurements;
    }

    @Id
    @Column(name = "dev_type_id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "dev_type", unique = true, length = 20)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "deviceType")
    public Set<Measurement> getMeasurements() {
        return this.measurements;
    }

    public void setMeasurements(Set<Measurement> measurements) {
        this.measurements = measurements;
    }

}
