package au.com.teamarrow.model;

// Generated 07/08/2013 11:47:52 PM by Hibernate Tools 4.0.0

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.joda.time.DateTime;

/**
 * MeasurementData generated by hbm2java
 */
@Entity
@Table(name = "msrmnt_data", schema = "public")
public class MeasurementData extends AbstractMeasurementData implements Serializable {

    private static final long serialVersionUID = 2034668092425278850L;
    
    public MeasurementData() {
        
    }

    public MeasurementData(Integer dataPointCanId, DateTime timestamp, Boolean extended, Boolean retry,
        Integer length, Double floatValue, Integer integerValue, String charValue, String state) {
        super(dataPointCanId, timestamp, extended, retry, length, floatValue, integerValue, charValue, state);
    }
    
    public MeasurementData(MeasurementData measurementData) {
    	super(measurementData.getDataPointCanId(),
    		  measurementData.getTimestamp(),
    		  measurementData.getExtended(),
    	      measurementData.getRetry(),
    	      measurementData.getLength(),
    	      measurementData.getFloatValue(),
    	      measurementData.getIntegerValue(),
    	      measurementData.getCharValue(),
    	      measurementData.getState());
    }

    @Id
    @Column(name = "msrmnt_data_id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getId() {
        return this.id;
    }
    
    public String toString() {
		return "dataPointCanId=" + this.getDataPointCanId() + 
				",timestamp=" + this.getTimestamp().toString() + 
				",fval="+ this.getFloatValue() +
				",ival=" + this.getIntegerValue() + 
				",cval=" + this.getCharValue();    	
    }
}
