package au.com.teamarrow.model;

// Generated 02/08/2013 12:30:48 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MeasurementType generated by hbm2java
 */
@Entity
@Table(name = "msrmnt_type", schema = "public")
public class MeasurementType implements java.io.Serializable {

    private long id;
    private String type;
    private Double lowErrorThreshold;
    private Double lowWarningThreshold;
    private Double highErrorThreshold;
    private Double highWarningThreshold;
    private Integer reportingFrequency;

    public MeasurementType() {
    }

    public MeasurementType(long Id) {
        this.id = Id;
    }

    public MeasurementType(long Id, String Type, Double LowErrorThreshold, Double LowWarningThreshold,
        Double HighErrorThreshold, Double HighWarningThreshold, Integer ReportingFrequency) {
        this.id = Id;
        this.type = Type;
        this.lowErrorThreshold = LowErrorThreshold;
        this.lowWarningThreshold = LowWarningThreshold;
        this.highErrorThreshold = HighErrorThreshold;
        this.highWarningThreshold = HighWarningThreshold;
        this.reportingFrequency = ReportingFrequency;
    }

    @Id
    @Column(name = "msrmnt_type_id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long Id) {
        this.id = Id;
    }

    @Column(name = "msrmnt_type", length = 100)
    public String getType() {
        return this.type;
    }

    public void setType(String Type) {
        this.type = Type;
    }

    @Column(name = "low_err_thrhld", precision = 17, scale = 17)
    public Double getLowErrorThreshold() {
        return this.lowErrorThreshold;
    }

    public void setLowErrorThreshold(Double LowErrorThreshold) {
        this.lowErrorThreshold = LowErrorThreshold;
    }

    @Column(name = "low_wrng_thrhld", precision = 17, scale = 17)
    public Double getLowWarningThreshold() {
        return this.lowWarningThreshold;
    }

    public void setLowWarningThreshold(Double LowWarningThreshold) {
        this.lowWarningThreshold = LowWarningThreshold;
    }

    @Column(name = "high_err_thrhld", precision = 17, scale = 17)
    public Double getHighErrorThreshold() {
        return this.highErrorThreshold;
    }

    public void setHighErrorThreshold(Double HighErrorThreshold) {
        this.highErrorThreshold = HighErrorThreshold;
    }

    @Column(name = "high_wrng_thrhld", precision = 17, scale = 17)
    public Double getHighWarningThreshold() {
        return this.highWarningThreshold;
    }

    public void setHighWarningThreshold(Double HighWarningThreshold) {
        this.highWarningThreshold = HighWarningThreshold;
    }

    @Column(name = "reprtng_frq")
    public Integer getReportingFrequency() {
        return this.reportingFrequency;
    }

    public void setReportingFrequency(Integer ReportingFrequency) {
        this.reportingFrequency = ReportingFrequency;
    }

}
